CREATE TABLE users(uid INT PRIMARY KEY AUTO_INCREMENT,firstname VARCHAR(100) NOT NULL,lastname VARCHAR(100) NOT NULL,email VARCHAR(120) UNIQUE NOT NULL,pwdhash VARCHAR(100) NOT NULL);
CREATE TABLE articles(id INT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(120) NOT NULL);
CREATE TABLE finished(id INT PRIMARY KEY AUTO_INCREMENT,state INT,uid INT,aid INT);